[package]
name = "crates-alfred-workflow"
version = "0.1.0"
authors = ["Ross MacArthur <ross@macarthur.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0"
fs2 = "0.4.3"
home = "0.5.3"
libc = "0.2.94"
once_cell = "1.7.2"
powerpack = "0.1.1"
semver = { version = "0.11.0", features = ["serde"] }
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
walkdir = "2.3.2"
