[package]
name = "crates-alfred-workflow"
version = "0.2.3"
authors = ["Ross MacArthur <ross@macarthur.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0.53"
chrono = "0.4.19"
dairy = "0.2.2"
either = "1.6.1"
fs2 = "0.4.3"
home = "0.5.3"
libc = "0.2.117"
log = { version = "0.4.14", features = ["std"] }
once_cell = "1.9.0"
powerpack = "0.2.2"
semver = { version = "1.0.5", features = ["serde"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
